version: '3'

services:
        xdmod10.0:
                image: tools-ext-01.ccr.xdmod.org/xdmod-10.0.0:rockylinux8.5-0.4
                container_name: xdmod10.0
                networks:
                        testing:
                                ipv4_address: 172.28.0.3
                volumes:
                        - ../xdmod.conf:/etc/httpd/conf.d/xdmod.conf
                        - ../xdmod:/root/src/github.com/ubccr/xdmod
                shm_size: 2g
                ports:
                        - 9006:443
                        - 7000:7000
                stdin_open: true
                tty: true
                command: >
                        /bin/bash -c "cd ~/src/github.com/ubccr/xdmod
                        && ./tests/ci/samlSetup.sh
                        && ~/bin/services nodaemon"
                healthcheck:
                        test: curl -k https://localhost || exit 1
                        interval: 10s
                        timeout: 5s
                        retries: 3
        playwright:
                image: mcr.microsoft.com/playwright:v1.22.0-focal
                container_name: playwright
                volumes:
                        - ../xdmod:/xdmod
                networks:
                        testing:
                                ipv4_address: 172.28.0.4
                stdin_open: true
                tty: true
                ipc: host
                links:
                        - xdmod10.0
                depends_on:
                        xdmod10.0:
                                condition: service_healthy
                environment:
                        BASE_URL: https://172.28.0.3
                        XDMOD_REALMS: 'jobs,storage,cloud'
                command: >
                        /bin/bash -c "cd /xdmod/tests/playwright
                        && ./runtests.sh -j test_results.xml
                        && tail -F anything"
                # tail -F null is for keeping the container up
                # playwright keeps exiting (receive PID 1 perhaps?)

networks:
        testing:
                ipam:
                        config:
                                - subnet: 172.28.0.0/16
