#THIS FILE IS FOR TESTING ALMA9 - IT DOES NOT WORK YET B/C PHP 8.0
FROM xdmod-base-alma9:latest

RUN yum -y install \
    rpm-build \
    openssl

RUN yum -y install \
    php \
    php-common \
    php-opcache \
    php-cli \
    php-gd \
    php-curl \
    php-pear \
    php-zip \
    php-gmp \
    php-pdo \
    php-xml \
    php-mbstring \
    php-mysqlnd \
    php-pecl-apcu \
    php-json \
    php-devel

# Install the mongodb pecl extension
RUN pecl install mongodb

# Enable the mongodb php extension
RUN echo "extension=mongodb.so" > /etc/php.d/40-mongodb.ini

# Make sure to clean the cache and installs.
RUN yum clean all && rm -rf /var/cache/yum

# Directory needed by php-fpm
RUN mkdir -p /run/php-fpm

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
    ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")" && \
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then echo 'ERROR: Invalid composer signature'; exit 1; fi && \
    php composer-setup.php --install-dir=/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" 
