# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:2022.08
jobs:
  build:
    parameters:
      os:
        type: string
      install-type:
        type: string
    executor: default
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      XDMOD_REALMS: 'jobs,storage,cloud'
      TRAVIS_COMMIT_RANGE: << pipeline.git.base_revision >>..<<pipeline.git.revision>>
      XDMOD_IS_CORE: yes
      XDMOD_INSTALL_DIR: /xdmod
      XDMOD_TEST_MODE: << parameters.install-type >>
    steps:
      - checkout
      # We need to update our acct before we can enable docker layer caching
      - setup_remote_docker
      #    docker_layer_caching: true
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      #- run: composer install --no-progress
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Download and Install Docker
          command: |
            apt update && apt install curl
            curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64" -o ~/docker-compose
            chmod +x ~/docker-compose  
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Docker Compose corresponding OS file
          command: docker compose up -d -f tests/ci/Docker/bin/<< parameters.os >>.yml
      - run:
          name: Copy Files for Playwright and XDMoD container
          command: |
            docker cp ~/project xdmod10.0:/xdmod
            docker cp ~/project playwright:/xdmod
      - run:
          name: Execute Install Script
          command: docker exec tests/ci/Docker/bin/install.sh
      - run:
          name: Execute Test Script
          command: docker exec tests/ci/Docker/bin/test.sh << parameters.os >>
      - run:
          name: Copy Test Results into Unit
          command: |
            docker cp xdmod10.0:/test-results ~/phpunit
            mkdir -p /var/log/xdmod
            mkdir -p /tmp/screenshots
            docker cp xdmod10.0:/tmp/screenshots /tmp/screenshots
            docker cp xdmod10.0:/var/log/xdmod /var/log/xdmod
            docker cp playwright:/tests/playwright/test_results.xml ~/phpunit
            docker cp playwright:/tests/playwright/test-results /tmp/screenshots
      - store_artifacts:
          path: /tmp/screenshots
      - store_artifacts:
          path: /var/log/xdmod
      - store_test_results:
          path: ~/phpunit
workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              os: ['centos7', 'centos8', 'rocky8']
              install-type: ["fresh_install", "upgrade"]
            exclude:
              - os: 'centos8'
                install-type: "upgrade"
              - os: 'rocky8'
                install-type: "upgrade"
